### ISSUE TITLE
a few important aspects

### ISSUE THREAD

**Issue by spacejam** [jimblandy/context-switch#1]
* hair-pin context switches (a thread -> kernel -> the same thread) are able to avoid TLB flushing, and is one reason behind why pinning causes measured differences with tasks to fade
* most pthread implementations on linux cache threads and don't actually create a new thread if a cached thread is available
* the 8mb of assigned stack memory is virtual - it doesn't actually use hardware until it gets used
* async tasks require pessimistic allocations for their worst-case stack, and for real-world use cases like a task that handles TLS and HTTP/GRPC/JSON, the measurable RESIDENT memory usage won't be all that different from threads overall
* async implementations may use epoll in oneshot mode, causing a lot of extra interest-related syscalls and increasing in-kernel contention. for workloads where there are more than one IO operation per socket, this can be particularly harmful for throughput. This causes throughput for async implementations to be significantly lower than the throughput of a threaded implementation, and a simple echo server can demonstrate this (see the req_res binaries [here](https://github.com/sled-rs/sled-rs.github.io/tree/master/hardware_timing/src/bin)).
* overall, there are a lot of things here that really fade into insignificance when you consider the simple effort required to deserialize JSON or handle TLS. People often see that there's some theoretical benefit of async and then they accept far less ergonomic coding styles and the additional bug classes that only happen on async due to accidental blocking etc... despite the fact that when you consider a real-world deployed application, those "benefits" become indistinguishable from noise. However, due to the additional bug classes and worse ergonomics, there is now less energy for actually optimizing the business logic, which is where all of the cycles and resource use are anyway, so in-practice async implementations tend to be buggier and slower.

**Comment by jimblandy** [comment]
> hair-pin context switches (a thread -> kernel -> the same thread) are able to avoid TLB flushing, and is one reason behind why pinning causes measured differences with tasks to fade

Interesting. But wouldn't a context switch between one thread and another thread in the same process also avoid TLB flushing?

**Comment by jimblandy** [comment]
Thanks very much for writing up your thoughts on this. My understanding of the tradeoffs between async and purely threaded designs has a lot of gaps, and part of my reason for posting the repo was to at least start a conversation.

> most pthread implementations on linux cache threads and don't actually create a new thread if a cached thread is available

I've seen that NPTL caches stacks. But I didn't see code (in glibc, at least) to cache the kernel tasks themselves, and I don't think I saw missing clone calls when I ran things under `strace`. Can you show me how to observe this?

But more fundamentally, I don't want to elevate implementation techniques above observed performance. Hopefully we agree that creating an async task is a lot faster than creating a Linux thread. If that is not the case, then there should be a microbenchmark I can run to see that it is not.

> the 8mb of assigned stack memory is virtual - it doesn't actually use hardware until it gets used

Yes - I point this out repeatedly. I talk about "pessimistically-sized thread stacks" and contrast that with resident set size. The section on "Measuring memory use" explains how I used linear regression on (proper) RSS measurements to come up with my cost of 9.5KiB / thread. The comment at the end about default thread stack sizes also describes lazy allocation of stack pages.

> async tasks require pessimistic allocations for their worst-case stack, and for real-world use cases like a task that handles TLS and HTTP/GRPC/JSON, the measurable RESIDENT memory usage won't be all that different from threads overall

I see your argument, but I would like to see measurements before I'd agree with the conclusion. An async task has its state divided between its future and the ordinary stack its `poll` calls run on. It seems possible that you could exclude a great deal of temporary state from the future, such that being able to share a single thread stack amongst many futures is a memory win.

But see below.

> overall, there are a lot of things here that really fade into insignificance when you consider the simple effort required to deserialize JSON or handle TLS. People often see that there's some theoretical benefit of async and then they accept far less ergonomic coding styles and the additional bug classes that only happen on async due to accidental blocking etc... despite the fact that when you consider a real-world deployed application, those "benefits" become indistinguishable from noise. However, due to the additional bug classes and worse ergonomics, there is now less energy for actually optimizing the business logic, which is where all of the cycles and resource use are anyway, so in-practice async implementations tend to be buggier and slower.

I have a few responses to this.

First of all, the reason I carried out the experiments in this repo in the first place was that I basically agreed with all of your points here. I think async is wildly oversold as "faster" without any real investigation into why that would be. It is very hard to pin down exactly how the alleged advantage would arise. The same I/O operations have to be carried out either way (or worse); kernel context switches have been heavily optimized over the years (although the Spectre mitigations made them worse); and the whole story of the creation of NPTL was about it beating IBM's competing M-on-N thread implementation (which I see as analogous to async task systems) in the very microbenchmarks in which the M-on-N thread library was expected to have an advantage.

However, in conversations that I sought out with people with experience implementing high-volume servers, both with threads and with async designs, my async skepticism met a lot of pushback. They consistently reported struggling with threaded designs and not being able to get performance under control until they went async. Big caveat: they were not using Rust - these were older designs in C++ and even C. But it jibes well with the other successful designs you see out there, like nginx and Elixir (which is used by WhatsApp, among others), which are all essentially async.

So the purpose of these experiments was to see if I could isolate the sources of async's apparent advantages. It came down to memory consumption, creation time, and context switch time each having best-case order-of-magnitude advantages. That is just beyond the point that I can call it negligible. How often the best case actually arises is unclear, but one can argue that that, at least, is under the programmer's control, so the ceiling on how far implementation effort can get you is higher, in an async design.

Ultimately, as far as this repo is concerned, you need to decide whether you trust your readers to understand both the value and the limitations of microbenchmarks. If you assume your readers are in Twitter mode---they're just going to glance at the headlines and come away with a binary, "async good, two legs bad" kind of conclusion---then maybe it's better not to publish microbenchmarks at all, because they're misleading. Reality is more sensitive to details. But I think the benefit of offering these microbenchmarks and the README's analysis to careful readers might(?) outweigh the harm done by the noise from careless readers, because I think the careful readers are more likely to use the material in a way that has lasting impact. The wind changes; the forest does not.

The 2nd edition of Programming Rust (due out in June) has a chapter on async that ends with a discussion of the rationale for async programming. It tries to dismiss some of the commonly heard bogus arguments, and present the advantages that async does have with the appropriate qualifications. It mentions tooling disadvantages. Generally, the chapter describes Rust's async implementation in a decent amount of detail, because we want our readers to be able to anticipate how it will perform and where it might help; the summary attempts to make clear what all that machinery can and cannot accomplish.

**Comment by jimblandy** [comment]
> async implementations may use epoll in oneshot mode, causing a lot of extra interest-related syscalls and increasing in-kernel contention. for workloads where there are more than one IO operation per socket, this can be particularly harmful for throughput. This causes throughput for async implementations to be significantly lower than the throughput of a threaded implementation, and a simple echo server can demonstrate this (see the req_res binaries [here](https://github.com/sled-rs/sled-rs.github.io/tree/master/hardware_timing/src/bin)).

I'm interested in looking into this more.

According to strace, `async-brigade` runs system calls like the following for each iteration:
```
recvfrom(238, "*", 1, 0, NULL, NULL)    = 1
write(241, "*", 1)                      = 1
recvfrom(238, 0x559169b0af51, 1, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(3, [{EPOLLOUT, {u32=233, u64=233}}, {EPOLLIN|EPOLLOUT, {u32=234, u64=234}}], 1024, 
-1) = 2
```

I don't see any `epoll` re-registration work here; it looks like `epoll` is being used correctly.

**Comment by photoszzt** [comment]
I'm curious what's the design people used in programming the web service with the thread model. You can use thread per connection or thread per request. With async, you can match that pattern with task per request. In this space, golang's interface(goroutine) is better than Rust. It's much easier to write. 

The other interesting aspect is tail latency. How would each desgin influence tail latency? A previous study talks about some of the findings: https://drkp.net/papers/latency-socc14.pdf

**Comment by jimblandy** [comment]
I'm sorry - I don't know much about web servers or Golang.

I suspect the microbenchmarks in this repo are too simplified to help illustrate much about the causes of poor latencies.

**Comment by spacejam** [comment]
```txt
But wouldn't a context switch between one thread and another thread in the same process also avoid TLB flushing?
```
Yeah, both of these are forms of hair-pin switches that are able to avoid TLB flushes compared to multi-process workloads like postgres etc...

```
I've seen that NPTL caches stacks. But I didn't see code (in glibc, at least) to cache the kernel tasks themselves, and I don't think I saw missing clone calls when I ran things under strace. Can you show me how to observe this?
```

The benefits of caching stacks are still pretty significant, as they allow for reducing the number of syscalls involved in mmapping things together. Syscall reduction is a huge win for many workloads, and is also one of the main benefits of well-made io_uring-based approaches. Here's how this is described in [the nptl manual from 2003](https://www.cs.utexas.edu/~witchel/372/lectures/POSIX_Linux_Threading.pdf):

![image](https://user-images.githubusercontent.com/1505488/107744747-877f3880-6d13-11eb-8119-f140319f4dc7.png)

To measure the effect, I might try to measure the difference between creating a small threadpool (small enough that the total stack memory is within the [40mb default stack cache](https://repo.or.cz/glibc.git/blob/HEAD:/nptl/allocatestack.c#l106).

1. Always control for turbo boost in comparative benchmarks, with the simplest way being to just disable it so that c-state frequency scaling doesn't impact things as much: `echo 1 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo`. This does not disable p-state scaling, which can be disabled on intel p-state machines by adding the `intel_pstate=disable` flag to the kernel boot line. Set the performance governor for good measure. 
2. Use `taskset` to restrict the measurement process to a single core so that the spawned thread uses the same rdtsc source
2. Perform some unoptimized computational work with no IO or syscalls to reduce some of the effect of cold-starts
3. measure the rdtsc each time before invoking `spawn`, and pass this to the spawned thread. measure in cycles instead of "time".
4. when the thread spawns, measure rdtsc (forced to the same core source by taskset) and record the latency in cycles between this measurement and the pre-spawn value.
5. do not let any of the spawned threads terminate until you have reached like 32mb cumulative stack sizes. You can configure the stack sizes to be smaller if you want to spawn more of them per process execution.
6. join all spawned threads, hopefully causing them to end up in the nptl stack cache
7. repeat the process using the same number of threads, and compare the latency distribution

It is more hazardous to measure this in Rust than C due to more stuff happening after spawn which will dilute the delta. 

```
But more fundamentally, I don't want to elevate implementation techniques above observed performance. Hopefully we agree that creating an async task is a lot faster than creating a Linux thread. If that is not the case, then there should be a microbenchmark I can run to see that it is not.
```
Yeah, it's faster to create, at the cost of additional syscalls during its execution to the extent that it interacts with epoll, which may be a strong net negative for throughput-oriented workloads.

```
I see your argument, but I would like to see measurements before I'd agree with the conclusion. An async task has its state divided between its future and the ordinary stack its poll calls run on. It seems possible that you could exclude a great deal of temporary state from the future, such that being able to share a single thread stack amongst many futures is a memory win.
```

I don't have metrics on hand, but I can say that sizing issues seems to come up for folks who try to actually achieve high concurrency with async tasks. I have a strong suspicion that async causes a lot more allocations than threaded workloads due to static-related issues. Tyler Mandry had some interesting metrics [at rustfest bcn](https://www.youtube.com/watch?v=ZHP9sUqB3Qs) about how at one point, many of the futures being used by fuchsia were megabytes in size. I'm not sure how much of the alleviation of their sizing issues was accomplished through compiler work vs just using more `Box`es in their futures.  Boats mentions this issue in the final section of [their post on future sizing](https://without.boats/blog/futures-and-segmented-stacks/) and offers the workaround of using Box to fragment the Future and reduce overall memory usage. This can backfire if that allocation ends up being present for most of the task's life anyway.

Zooming out, I tend to think of this sort of similarly to highways adding more lanes and getting worse traffic. Making certain things easy causes induced demand, and the negative effects of those easier and now more common things can be worse than the problems they supposedly addressed in the first place. In general, concurrency tends to increase memory usage. You have to put things on the heap to share them (ignoring crossbeam scopes etc...), which will always be a bit more fragmented than the stack. Then, [there is a trade-off in many concurrent structures that will trade additional memory usage for lower contention](http://sled.rs/perf#memory-pressure-vs-contention). This trade-off is kind of subtle and I don't think even many concurrent data structure authors think very explicitly about it. But the more concurrent we are, there is a tendency to increase memory usage in order to avoid contention. The process of optimizing concurrent data structures often involves finding contention and reducing it, which often can be accomplished by using more memory. So, concurrent data structures often get faster over time while simultaneously becoming more gluttonous. Async opts into this general trade-off trajectory without really being mindful of it.

```
However, in conversations that I sought out with people with experience implementing high-volume servers, both with threads and with async designs, my async skepticism met a lot of pushback. They consistently reported struggling with threaded designs and not being able to get performance under control until they went async. Big caveat: they were not using Rust - these were older designs in C++ and even C. But it jibes well with the other successful designs you see out there, like nginx and Elixir (which is used by WhatsApp, among others), which are all essentially async.
```
Everyone working in distributed systems seems to have at one point or another come across [The C10K problem](http://www.kegel.com/c10k.html) and everyone seems to accept it as cannon. As humans, we tend not to re-verify things that have been historically true. We just accept them as the truth until the truth blows up in our face. In 1999 when this was written, the strategies presented were the ones that made sense in 1999. It is no longer 1999, but C10K is cannon. Many things that were scarce then are not scarce now. Threads really were a lot worse back then, driving an extreme need for minimizing their use at all costs. The hair-pin tricks were not in place. Syscalls were not proportionally as big of a deal as they are today. Memory was less plentiful. Today, the memory we devote to a thread tends to be proportionally a lot less than it was in 1999. Look at Erlang - currently a process requires over 300 words. It used to require 200ish. Supporting 64-bit doubled the bytes in a word. Over time, the memosy cost of a task has almost quadroupled, but nobody is the least bit concerned, because this is not significant. HOWEVER - even in 1999, using epoll etc... still caused throughput to drop for workloads that had very low concurrency to begin with. But given that the benefits started to show with even a dozen connections, event-driven approaches were generally the right way to go for a wider variety of workloads.

Today, the number of workloads that event-driven architectures actually show a measurable improvement on are fairly low. Yes, they are important for building load balancers. That's why the company that was funding so much Tokio work was a load balancer company. But it is not the days of C10k where you need to use epoll if you want to run a chat server with a few dozen users. Humans don't update their assumptions until the assumptions blow up in their face. And the additional compiler errors that blow up in Rust users faces are unfortunately somethign that Rust users quickly learn to accept as they pick up the language. They don't know where the point is that they should actually not be tolerant of so much compiler friction. This may take a few years of being burned by complexity to get a sense of, and may never happen unless one has a mind for reducing the pain in their lives.

```
I don't see any epoll re-registration work here; it looks like epoll is being used correctly.
```

Well, the issue here is that the underlying event system is configurable, and different configurations are important for serving specific workloads well. Low-concurrency, high-throughput workloads will almost never be as fast in async Rust due to incurring more work handling multiplexing that is already being done in the kernel. The 1 client 1 server throughput-oriented echo example illustrates this pretty vividly. 

From an educational perspective, I agree that async should have a place in a book, and that you are quite well positioned to encourage the ecosystem to avoid pain by teaching its costs rather than the hyped aspects alone. When I've given 3-day Rust workshops to teams building distributed systems with very high reliability and performance needs, I've been very explicit about how hazardous the additional complexity is from a human productivity perspective, how it creates additional verification burden due to the new bug classes, how throughput may drop significantly in cases where you would have dedicated an entire core to a client anyway, and how you will need to write your own executor in some cases if you care about [scheduling considerations](http://sled.rs/perf#scheduling) (as any system that needs to handle mutli-tenant workloads with careful attention to quality of service issues will need to, since the popular executors are only suitable for completely homogeneous workloads). So, I've taught it to these specialized audiences as "yes, you can use this, and here is the cost of doing so which may not be obvious from the hype." 

```
The newer io_uring-style APIs seem radically different, and I'm curious to see whether these might change the story here.
```

This is an absolute game-changer. I've spoken strongly in-favor of io_uring [here](https://archive.fosdem.org/2020/schedule/event/rust_techniques_sled/) and I believe this is the most important kernel change in many years. The event-driven APIs which increase total syscalls and exist for multiplexing work onto threads as a latency optimization at the cost of per-socket throughput. They are a [saturation-driven optimization rather than an efficiency-driven optimization](https://twitter.com/sadisticsystems/status/1351840268677505026). io_uring, on the other hand, is an efficiency-driven optimization that improves both latency AND throughput for nearly every workload. The efficiency gains come from avoiding syscalls, avoiding mapping effort that must happen when the kernel wants to use memory that is mapped to userspace, avoiding buffer copying that must happen before the kernel normally puts something into an sk_buff etc... It can even be configured to run without any manual syscalls at all by setting up a polling thread in the kernel which spins on the receive queue that is shared between userspace and kernelspace. I've yet to see any libraries that really lean into the zero-copy io topologies that become possible with io_uring, and this remains a really exciting frontier for performance work over time. It has nothing to do with async rust. 

By the way, it makes me really happy to see anyone measuring things at all these days :) Nice work!

**Comment by jimblandy** [comment]
(Still reading and digesting. Initial reaction is, this is great stuff and should be a blog post somewhere.)

**Comment by jimblandy** [comment]
> Everyone working in distributed systems seems to have at one point or another come across The C10K problem and everyone seems to accept it as canon. As humans, we tend not to re-verify things that have been historically true. We just accept them as the truth until the truth blows up in our face.

No disagreement here, about human tendencies. In this specific case, I *think* the folks I spoke to were under enough competitive pressure that they'd have needed to make a pretty clear-eyed assessment of the alternatives. One was doing HFT [ed: High-Frequency Trading], and apparently the C++ async proposal authors are also in HFT. But of course, whether they explored the question exhaustively, I don't know.

The perfect apples-to-apples comparison would be a production-ready system that can be either async or thread-based at the flip of a switch, that makes idiomatic use of each alternative, and with no other architectural differences between the two. But I'm not holding my breath.

> From an educational perspective, I agree that async should have a place in a book, and that you are quite well positioned to encourage the ecosystem to avoid pain by teaching its costs rather than the hyped aspects alone.

Thanks very much! In all honesty, I can't promise that you will approve of our async chapter. There are pretty strict limits on length - at 675 pages for the whole book (excluding beginning and end material), we're at the limits of certain book-binding techniques, and of the book price point, and of what we can reasonably expect our audience to digest. I've tried to get the essentials across, but there's so much that's left unsaid. So I won't even be able to help readers avoid the common problems. But I'm aiming to at least put them in a position where they can figure out what's going on if troubles arise.

**Comment by spacejam** [comment]
Yeah, HFT is one of the few remaining spaces where the compute hit due to kernel scheduling compared to a well-made event scheduler is measurable and in some cases significant, depending on how much concurrency is used at all (it is usually important to minimize this in cases where you want your queues absolutely unsaturated for minimizing latency and just throwing more machines at the problem to the extent that it doesn't reduce cache performance by being spread too thin). But in these cases, you would also stand to significantly gain performance by completely avoiding the Rust `Future` interface-based scheduling approach, which provides no clear mechanism for providing QoS or prioritization. You have to use hacks like passing state through thread-local side-channels to the custom scheduler if you want this kind of intelligence in the scheduler. A few big-name rust projects have [seen a lot of improvements by completely slicing out rust async while continuing to use evented IO directly](https://github.com/firecracker-microvm/firecracker/commit/f01e5b0d1de954c2ec4f1ecbd23c6f1299b411fd). 

Re: apples to apples, this is always aspirational as even our machines physically change from one moment to the next, but it goes a long way by using representative mixes of resources in representative patterns. It's usually pretty easy to get high quality estimates. But very few engineers are ever rewarded for the effort of doing so, so we have a culture of ignorance.

**Comment by kprotty** [comment]
> You have to use hacks like passing state through thread-local side-channels to the custom scheduler if you want this kind of intelligence in the scheduler

There's another hack available which is to use the `&mut Context` (and specifically the `.waker()` from it) in order to derive Thread/Task local state for setting stuff like priority, affinity, etc. Either ways, the cost of needing to sync/update the waker on re-polls, wakers outliving futures, chain-polling down the future poll-depth on resume, and other inefficiencies still make rust async not a pleasant experience when resource efficiency is the goal.

**Comment by pdeva** [comment]
An article[1] relevant to this dicussion seems to be from the folks working on virtual threads in the JVM. My reading of this is that  they conclude that context switching in itself is not worth optimizing for so much in virtual threads. The big gains come from the fact that you can submit order of magnitude more work to the IO system due to increased concurrency.

[1] https://inside.java/2020/08/07/loom-performance/

**Comment by jimblandy** [comment]
Oh, that blog post is excellent. Thanks for the link!

As I say in the introduction, "[Context switches] are probably not the limiting factor in your application". This is a microbenchmark, and the prefix 'micro' there is supposed to flag to folks that it's not trying to model any real-world load.

But elsewhere I have been trying to help people understand the conditions under which async programming is valuable, because I think it's been over-sold a bit, and for that purpose that blog post is very helpful and right on the mark.

I'm a fan of Pressler's also for his work on other stuff: https://www.youtube.com/watch?v=dWdy_AngDp0

But it seems to me he drops the ball right when it gets good:

> Clearly, to significantly increase the capacity of such a system [we should] focus on increasing L, the number of transactions we can process concurrently. If we keep the simple thread-per-request programming model and process each transaction on a single thread, L would be the number of active threads we need. And that is how user-mode threads help: they increase L by orders of magnitude with potentially millions of user-mode threads instead of the meager thousands the OS can support (but don’t expect a 1000x increase in capacity; we’ve neglected computation costs and are bound to hit bottlenecks in the auxiliary services). Asynchronous programming also improves performance in the same way: not by reducing task-switching costs, but by increasing L, the number of transactions concurrently processed, only it doesn’t represent each transaction with a thread but with a different construct.

He doesn't say *what difference* enables these increases, either when comparing kernel to user-mode threads, or when comparing user-mode threads to async's "different construct".

As far as I can tell, the key difference is memory consumption. Rust async tasks draw a distinction between state that needs to be retained across async context switches, and state that does not: the former is stored in the future, and the latter is stored on the thread stack. (I assume Loom does something similar.) If all blocking is handled using the async mechanisms, then there is no need to run more threads than processor cores, so all that latter state can be held in a fixed number of stacks; it's not influenced by the number of async tasks you're running. So the async advantage arises if and when the futures are significantly smaller than the stacks.

Pressler is saying that we improve throughput by increasing the number of transactions concurrently processed. I'm guessing that async lets us increase the number of transactions (when it does) by reducing the memory consumption of each transaction in flight, allowing us to run more.

**Comment by pdeva** [comment]
I agree that memory consumption is the key difference.

Also adding some points that further contribute to vthreads performance:

1. most people spawn threads inside a managed runtime like JVM or .Net. These runtimes do occupy a significant chunk of memory per thread (on top of what the kernel uses). This post[1] says the JVM occupies 16kb per thread.
2. GC algorithms, which have to start their scans per thread are probably designed with hundreds of threads in mind and have corresponding internal data structures. Those data structures probably dont take a million threads into account and will perform badly with extremely high thread count.
3. runtimes like Go and Tokio do 'work stealing' to distribute vthreads across cores. That means most vthreads will execute most of the time on the core they spawned upon. This gives them better locality of data. That said, I am not sure how the linux kernel schedules threads and how much it tries to keep each thread on the spawning core. 

[1] [https://jsravn.com/2019/05/01/jvm-thread-actual-memory-usage](https://jsravn.com/2019/05/01/jvm-thread-actual-memory-usage)
